author: jswing83
category: Effects
current: v0.1
description: Animate image sprites frame by frame.
demo: http://jsfiddle.net/jswing83/SSXmw/
docs: http://jswing83.github.com/Fx.Sprite/
name: Fx.Sprite
tags: [animation, sprite, background-position, Fx]